## Assignment 0:

**Due Date:** 17.04.2024, 23:59 Central European Summer Time (CEST)</br>
**Grade:** Ungraded and Compulsory

### Task 1: Bank Account Class

Define a class called **BankAccount** that emulates an actual bank account. The class should have two attributes namely *account_holder* which holds the name of the account holder as a *string* and *balance* which holds the current balance (in €) of the account. The class should have three methods namely **deposit()**, **withdraw()** and **display_balance()**. Please note that only integer currencies are allowed in your bank i.e. the minimum possible denomination for deposit and withdrawal is 1 €. You should enforce this condition throughout your code even if not mentioned explicitely.

#### Steps:
1.) The **deposit** method adds *amount* to the account *balance* and it should only deposit the *amount* if it is a positive integer. After calling this method, it should print *"\<amount\> has been deposited. New balance is \<new balance\>"*. If the *amount* is negative or of invalid data-type it should print *"Deposit amount must be positive"*. </br>

2.) The **withdraw** method should reduce the *balance* by the *amount* withdrawn by the account holder only if the *amount* is a positive integer. If the *amount* being withdrawn is greater than the *balance*, it should print *Insufficient funds*. If the withdraw was successful, it should print *"\<amount\> withdrawn. New balance is \<new balance\>"*.</br>

3.) The **display_balance** method, when called, should display the current *balance* of the account by printing *"The current balance is \<balance\>."* </br>

4.) Open your own bank account called *my_account*. Pass your name as the *account_holder* and define a starting balance of *100 €*. </br>

5.) Run the test code that is provided below to check for the correctness of your code.

**Note:** <...> brackets are used as place holders where actual values should be replaced by your code.

In [ ]:
# Steps 1-3: Define your Bank Account Class below 💸
# ----------




In [ ]:
# Step 4: Create your own bank account below
# -------




In [ ]:
# Step 5: Test your class (Do not modify the code)
# -------
my_account.deposit(150)
my_account.withdraw(80)
print(f"The current balance is {my_account.balance} Euro")

**Expected output:** The current balance is 170 Euro.

### Task 2: Analyzing Weather Data (NumPy exercise)

The daily temperature data for 4 different cities for the whole week is given below as a numpy array of shape (7, 4, 3). Here, 7 represents the 7 days in a week with Sunday being the first day of the week. 4 represents the 4 different cities namely *Berlin*, *Hamburg*, *Ingolstadt* and *Frankfurt* respectively. 3 represents *morning*, *afternoon* and *evening* respectively.

Please solve all five sub-tasks from *2.1* to *2.5*.

In [ ]:
# Given weather data: Please do not modify the below code
# -------------------
import numpy as np

np.random.seed(100)
temperature_data = np.random.randint(low=1, high=20, size=(7, 4, 3), dtype=np.int8)

print("Given temperature data:  \n", temperature_data)

#### Sub-task 2.1: 

Get Monday's morning temperature in Ingolstadt.

In [ ]:
# Your code below:
# ----------------




**Expected output:** Monday's morning temperature in Ingolstadt is 11 deg C.

#### Sub-task 2.2: 

Get the days (indices) when Berlin had a morning temperature that was less than 10 deg C.

In [ ]:
# Your code below:
# ----------------




**Expected output:** Indices of days when Berlin had a morning temperature < 10 deg C: </br>
 [[0]</br>
 [2]</br>
 [3]</br>
 [6]]

#### Sub-task 2.3: 

Add the 7-day temperature data of Munich which is given below to the *temperature_data* and overwrite it.

In [ ]:
# Given Munich data: Please do not modify the below code
# ------------------
np.random.seed(100)
munich_data = np.random.randint(low=1, high=20, size=(7, 3), dtype=np.int8)

# Your code below:
# ----------------




**Expected output:** New temperature dataset: </br>
 [[[ 9 12 17]</br>
  [12  4  4]</br>
  [ 8  8 10]</br>
  [16 14 13]</br>
  [ 9 12 17]]</br>
</br>
 [[16  1  2]</br>
  [ 7 17  4]</br>
  [11 11  7]</br>
  [ 2  2  9]</br>
  [12  4  4]]</br>

 [[ 3  8 17]</br>
  [16  3 12]</br>
  [ 3 10 15]</br>
  [12  3  4]</br>
  [ 8  8 10]]</br>

 [[ 7 18  3]</br>
  [17 11  2]</br>
  [18 16  7]</br>
  [14 17  5]</br>
  [16 14 13]]</br>

 [[13 14  5]</br>
  [12  8 19]</br>
  [ 6 15  6]</br>
  [17 12 18]</br>
  [16  1  2]]</br>

 [[16  6 19]</br>
  [16 10  2]</br>
  [ 3 10 15]</br>
  [ 8 13  8]</br>
  [ 7 17  4]]</br>

 [[ 5 11 16]</br>
  [10 13  1]</br>
  [ 2  5 13]</br>
  [14 13 17]</br>
  [11 11  7]]]

#### Sub-task 2.4: 

Calculate the daily average temperature of each city for the entire week. 

In [ ]:
# Your code below:
# ---------------




*Expected output:** Daily average temperature of each city for the whole week:</br> 
 [[12.66666667  6.66666667  8.66666667 14.33333333 12.66666667]</br>
 [ 6.33333333  9.33333333  9.66666667  4.33333333  6.66666667]</br>
 [ 9.33333333 10.33333333  9.33333333  6.33333333  8.66666667]</br>
 [ 9.33333333 10.         13.66666667 12.         14.33333333]</br>
 [10.66666667 13.          9.         15.66666667  6.33333333]</br>
 [13.66666667  9.33333333  9.33333333  9.66666667  9.33333333]</br>
 [10.66666667  8.          6.66666667 14.66666667  9.66666667]]

#### Sub-task 2.5: 

Find the *city/cities* with the lowest daily temperature variation (max-min). Also find the respective *day*. The result can be a 2D numpy array with day and city information as shown in the **Expected output** below.

In [ ]:
# Your code below:
# ----------------




**Expected output:** Days, cities with the lowest daily temperature variation: </br>
 [[0 2]</br>
 [2 4]]</br>

 Here, [0 2] indicates that the lowest temperature variation (max-min) i.e. 2 deg C was on a Sunday in Ingolstadt and [2 4] indicates that the same 2 deg C variation which is the lowest for the dataset provided was found on a Tuesday in Munich.