In [1]:
class BankAccount:
    def __init__(self, account_holder, balance):
        self.account_holder = account_holder
        self.balance = balance

    def deposit(self, amount):
        if isinstance( amount, int ) and amount >= 1:
            self.balance += amount
            print(f"{amount} € has been deposited. New balance is {self.balance} €.")
        else:
            print("Deposit amount must be positive")
            
    def withdraw(self, amount):
        if isinstance( amount, int ) and amount >= 1:
            if (amount > self.balance):
                print("Insufficient funds")
            else:
                self.balance = self.balance - amount
                print(f"{amount} € withdrawn. New balance is {self.balance} €.")
        else:
            print("Deposit amount must be positive")

    def display_balance(self):
        print(f"The current balance is {self.balance} €.")
            
my_account = BankAccount("Md Shiful Islam", 100)

#my_account.deposit(150)
#my_account.withdraw(80)
#my_account.display_balance()

my_account.deposit(150)
my_account.withdraw(80)
print(f"The current balance is {my_account.balance} Euro")

150 € has been deposited. New balance is 250 €.
80 € withdrawn. New balance is 170 €.
The current balance is 170 Euro


In [1]:
# Given weather data: Please do not modify the below code
# -------------------
import numpy as np

np.random.seed(100)
temperature_data = np.random.randint(low=1, high=20, size=(7, 4, 3), dtype=np.int8)

print("Given temperature data:  \n", temperature_data)

Given temperature data:  
 [[[ 9 12 17]
  [12  4  4]
  [ 8  8 10]
  [16 14 13]]

 [[16  1  2]
  [ 7 17  4]
  [11 11  7]
  [ 2  2  9]]

 [[ 3  8 17]
  [16  3 12]
  [ 3 10 15]
  [12  3  4]]

 [[ 7 18  3]
  [17 11  2]
  [18 16  7]
  [14 17  5]]

 [[13 14  5]
  [12  8 19]
  [ 6 15  6]
  [17 12 18]]

 [[16  6 19]
  [16 10  2]
  [ 3 10 15]
  [ 8 13  8]]

 [[ 5 11 16]
  [10 13  1]
  [ 2  5 13]
  [14 13 17]]]


In [3]:
print(f"Monday's morning temperature in Ingolstadt is {temperature_data[1, 2, 0]} deg C.")

Monday's morning temperature in Ingolstadt is 11 deg C.


In [5]:
berlin_morning_indices = np.where(temperature_data[:, 0, 0] < 10)[0]
print("Indices of days when Berlin had a morning temperature < 10 deg C:")
print(berlin_morning_indices.reshape(-1, 1))

Indices of days when Berlin had a morning temperature < 10 deg C:
[[0]
 [2]
 [3]
 [6]]


In [2]:
np.random.seed(100)
munich_data = np.random.randint(low=1, high=20, size=(7, 3), dtype=np.int8)

munich_data_reshaped = munich_data.reshape(7, 1, 3)
temperature_data = np.concatenate((temperature_data, munich_data_reshaped), axis=1)
print("\n New temperature dataset: \n", temperature_data)



 New temperature dataset: 
 [[[ 9 12 17]
  [12  4  4]
  [ 8  8 10]
  [16 14 13]
  [ 9 12 17]]

 [[16  1  2]
  [ 7 17  4]
  [11 11  7]
  [ 2  2  9]
  [12  4  4]]

 [[ 3  8 17]
  [16  3 12]
  [ 3 10 15]
  [12  3  4]
  [ 8  8 10]]

 [[ 7 18  3]
  [17 11  2]
  [18 16  7]
  [14 17  5]
  [16 14 13]]

 [[13 14  5]
  [12  8 19]
  [ 6 15  6]
  [17 12 18]
  [16  1  2]]

 [[16  6 19]
  [16 10  2]
  [ 3 10 15]
  [ 8 13  8]
  [ 7 17  4]]

 [[ 5 11 16]
  [10 13  1]
  [ 2  5 13]
  [14 13 17]
  [11 11  7]]]


In [6]:
daily_avg_temperature = np.mean(temperature_data, axis=2)
print("Daily average temperature of each city for the whole week:")
print(daily_avg_temperature)

Daily average temperature of each city for the whole week:
[[12.66666667  6.66666667  8.66666667 14.33333333 12.66666667]
 [ 6.33333333  9.33333333  9.66666667  4.33333333  6.66666667]
 [ 9.33333333 10.33333333  9.33333333  6.33333333  8.66666667]
 [ 9.33333333 10.         13.66666667 12.         14.33333333]
 [10.66666667 13.          9.         15.66666667  6.33333333]
 [13.66666667  9.33333333  9.33333333  9.66666667  9.33333333]
 [10.66666667  8.          6.66666667 14.66666667  9.66666667]]


In [8]:
temp_variation = np.max(temperature_data, axis=2) - np.min(temperature_data, axis=2)
min_temp_variation = np.min(temp_variation)
min_indices = np.argwhere(temp_variation == min_temp_variation)
print("Days, cities with the lowest daily temperature variation:")
print(min_indices)

Days, cities with the lowest daily temperature variation:
[[0 2]
 [2 4]]
